set_false_path -from * -to [get_ports hps_io_hps_io_emac1_inst_TX_CLK]
set_false_path -from * -to [get_ports hps_io_hps_io_emac1_inst_TXD0]
set_false_path -from * -to [get_ports hps_io_hps_io_emac1_inst_TXD1]
set_false_path -from * -to [get_ports hps_io_hps_io_emac1_inst_TXD2]
set_false_path -from * -to [get_ports hps_io_hps_io_emac1_inst_TXD3]
set_false_path -from [get_ports hps_io_hps_io_emac1_inst_RXD0] -to *
set_false_path -from [get_ports hps_io_hps_io_emac1_inst_MDIO] -to *
set_false_path -from * -to [get_ports hps_io_hps_io_emac1_inst_MDIO]
set_false_path -from * -to [get_ports hps_io_hps_io_emac1_inst_MDC]
set_false_path -from [get_ports hps_io_hps_io_emac1_inst_RX_CTL] -to *
set_false_path -from * -to [get_ports hps_io_hps_io_emac1_inst_TX_CTL]
set_false_path -from [get_ports hps_io_hps_io_emac1_inst_RX_CLK] -to *
set_false_path -from [get_ports hps_io_hps_io_emac1_inst_RXD1] -to *
set_false_path -from [get_ports hps_io_hps_io_emac1_inst_RXD2] -to *
set_false_path -from [get_ports hps_io_hps_io_emac1_inst_RXD3] -to *