// ledtest_mm_interconnect_2.v

// This file was auto-generated from altera_mm_interconnect_hw.tcl.  If you edit it your changes
// will probably be lost.
// 
// Generated using ACDS version 17.0 595

`timescale 1 ps / 1 ps
module ledtest_mm_interconnect_2 (
		input  wire         CLOCK_clk_clk,                                                        //                                                      CLOCK_clk.clk
		input  wire         ARM_MCU_f2h_sdram0_data_translator_reset_reset_bridge_in_reset_reset, // ARM_MCU_f2h_sdram0_data_translator_reset_reset_bridge_in_reset.reset
		input  wire         JTAG_DEBUG_clk_reset_reset_bridge_in_reset_reset,                     //                     JTAG_DEBUG_clk_reset_reset_bridge_in_reset.reset
		input  wire         JTAG_DEBUG_master_translator_reset_reset_bridge_in_reset_reset,       //       JTAG_DEBUG_master_translator_reset_reset_bridge_in_reset.reset
		input  wire [31:0]  JTAG_DEBUG_master_address,                                            //                                              JTAG_DEBUG_master.address
		output wire         JTAG_DEBUG_master_waitrequest,                                        //                                                               .waitrequest
		input  wire [3:0]   JTAG_DEBUG_master_byteenable,                                         //                                                               .byteenable
		input  wire         JTAG_DEBUG_master_read,                                               //                                                               .read
		output wire [31:0]  JTAG_DEBUG_master_readdata,                                           //                                                               .readdata
		output wire         JTAG_DEBUG_master_readdatavalid,                                      //                                                               .readdatavalid
		input  wire         JTAG_DEBUG_master_write,                                              //                                                               .write
		input  wire [31:0]  JTAG_DEBUG_master_writedata,                                          //                                                               .writedata
		output wire [26:0]  ARM_MCU_f2h_sdram0_data_address,                                      //                                        ARM_MCU_f2h_sdram0_data.address
		output wire         ARM_MCU_f2h_sdram0_data_write,                                        //                                                               .write
		output wire         ARM_MCU_f2h_sdram0_data_read,                                         //                                                               .read
		input  wire [255:0] ARM_MCU_f2h_sdram0_data_readdata,                                     //                                                               .readdata
		output wire [255:0] ARM_MCU_f2h_sdram0_data_writedata,                                    //                                                               .writedata
		output wire [7:0]   ARM_MCU_f2h_sdram0_data_burstcount,                                   //                                                               .burstcount
		output wire [31:0]  ARM_MCU_f2h_sdram0_data_byteenable,                                   //                                                               .byteenable
		input  wire         ARM_MCU_f2h_sdram0_data_readdatavalid,                                //                                                               .readdatavalid
		input  wire         ARM_MCU_f2h_sdram0_data_waitrequest                                   //                                                               .waitrequest
	);

	wire          jtag_debug_master_translator_avalon_universal_master_0_waitrequest;   // JTAG_DEBUG_master_agent:av_waitrequest -> JTAG_DEBUG_master_translator:uav_waitrequest
	wire   [31:0] jtag_debug_master_translator_avalon_universal_master_0_readdata;      // JTAG_DEBUG_master_agent:av_readdata -> JTAG_DEBUG_master_translator:uav_readdata
	wire          jtag_debug_master_translator_avalon_universal_master_0_debugaccess;   // JTAG_DEBUG_master_translator:uav_debugaccess -> JTAG_DEBUG_master_agent:av_debugaccess
	wire   [31:0] jtag_debug_master_translator_avalon_universal_master_0_address;       // JTAG_DEBUG_master_translator:uav_address -> JTAG_DEBUG_master_agent:av_address
	wire          jtag_debug_master_translator_avalon_universal_master_0_read;          // JTAG_DEBUG_master_translator:uav_read -> JTAG_DEBUG_master_agent:av_read
	wire    [3:0] jtag_debug_master_translator_avalon_universal_master_0_byteenable;    // JTAG_DEBUG_master_translator:uav_byteenable -> JTAG_DEBUG_master_agent:av_byteenable
	wire          jtag_debug_master_translator_avalon_universal_master_0_readdatavalid; // JTAG_DEBUG_master_agent:av_readdatavalid -> JTAG_DEBUG_master_translator:uav_readdatavalid
	wire          jtag_debug_master_translator_avalon_universal_master_0_lock;          // JTAG_DEBUG_master_translator:uav_lock -> JTAG_DEBUG_master_agent:av_lock
	wire          jtag_debug_master_translator_avalon_universal_master_0_write;         // JTAG_DEBUG_master_translator:uav_write -> JTAG_DEBUG_master_agent:av_write
	wire   [31:0] jtag_debug_master_translator_avalon_universal_master_0_writedata;     // JTAG_DEBUG_master_translator:uav_writedata -> JTAG_DEBUG_master_agent:av_writedata
	wire    [2:0] jtag_debug_master_translator_avalon_universal_master_0_burstcount;    // JTAG_DEBUG_master_translator:uav_burstcount -> JTAG_DEBUG_master_agent:av_burstcount
	wire          rsp_mux_src_valid;                                                    // rsp_mux:src_valid -> JTAG_DEBUG_master_agent:rp_valid
	wire  [111:0] rsp_mux_src_data;                                                     // rsp_mux:src_data -> JTAG_DEBUG_master_agent:rp_data
	wire          rsp_mux_src_ready;                                                    // JTAG_DEBUG_master_agent:rp_ready -> rsp_mux:src_ready
	wire    [0:0] rsp_mux_src_channel;                                                  // rsp_mux:src_channel -> JTAG_DEBUG_master_agent:rp_channel
	wire          rsp_mux_src_startofpacket;                                            // rsp_mux:src_startofpacket -> JTAG_DEBUG_master_agent:rp_startofpacket
	wire          rsp_mux_src_endofpacket;                                              // rsp_mux:src_endofpacket -> JTAG_DEBUG_master_agent:rp_endofpacket
	wire  [255:0] arm_mcu_f2h_sdram0_data_agent_m0_readdata;                            // ARM_MCU_f2h_sdram0_data_translator:uav_readdata -> ARM_MCU_f2h_sdram0_data_agent:m0_readdata
	wire          arm_mcu_f2h_sdram0_data_agent_m0_waitrequest;                         // ARM_MCU_f2h_sdram0_data_translator:uav_waitrequest -> ARM_MCU_f2h_sdram0_data_agent:m0_waitrequest
	wire          arm_mcu_f2h_sdram0_data_agent_m0_debugaccess;                         // ARM_MCU_f2h_sdram0_data_agent:m0_debugaccess -> ARM_MCU_f2h_sdram0_data_translator:uav_debugaccess
	wire   [31:0] arm_mcu_f2h_sdram0_data_agent_m0_address;                             // ARM_MCU_f2h_sdram0_data_agent:m0_address -> ARM_MCU_f2h_sdram0_data_translator:uav_address
	wire   [31:0] arm_mcu_f2h_sdram0_data_agent_m0_byteenable;                          // ARM_MCU_f2h_sdram0_data_agent:m0_byteenable -> ARM_MCU_f2h_sdram0_data_translator:uav_byteenable
	wire          arm_mcu_f2h_sdram0_data_agent_m0_read;                                // ARM_MCU_f2h_sdram0_data_agent:m0_read -> ARM_MCU_f2h_sdram0_data_translator:uav_read
	wire          arm_mcu_f2h_sdram0_data_agent_m0_readdatavalid;                       // ARM_MCU_f2h_sdram0_data_translator:uav_readdatavalid -> ARM_MCU_f2h_sdram0_data_agent:m0_readdatavalid
	wire          arm_mcu_f2h_sdram0_data_agent_m0_lock;                                // ARM_MCU_f2h_sdram0_data_agent:m0_lock -> ARM_MCU_f2h_sdram0_data_translator:uav_lock
	wire  [255:0] arm_mcu_f2h_sdram0_data_agent_m0_writedata;                           // ARM_MCU_f2h_sdram0_data_agent:m0_writedata -> ARM_MCU_f2h_sdram0_data_translator:uav_writedata
	wire          arm_mcu_f2h_sdram0_data_agent_m0_write;                               // ARM_MCU_f2h_sdram0_data_agent:m0_write -> ARM_MCU_f2h_sdram0_data_translator:uav_write
	wire   [12:0] arm_mcu_f2h_sdram0_data_agent_m0_burstcount;                          // ARM_MCU_f2h_sdram0_data_agent:m0_burstcount -> ARM_MCU_f2h_sdram0_data_translator:uav_burstcount
	wire          arm_mcu_f2h_sdram0_data_agent_rf_source_valid;                        // ARM_MCU_f2h_sdram0_data_agent:rf_source_valid -> ARM_MCU_f2h_sdram0_data_agent_rsp_fifo:in_valid
	wire  [364:0] arm_mcu_f2h_sdram0_data_agent_rf_source_data;                         // ARM_MCU_f2h_sdram0_data_agent:rf_source_data -> ARM_MCU_f2h_sdram0_data_agent_rsp_fifo:in_data
	wire          arm_mcu_f2h_sdram0_data_agent_rf_source_ready;                        // ARM_MCU_f2h_sdram0_data_agent_rsp_fifo:in_ready -> ARM_MCU_f2h_sdram0_data_agent:rf_source_ready
	wire          arm_mcu_f2h_sdram0_data_agent_rf_source_startofpacket;                // ARM_MCU_f2h_sdram0_data_agent:rf_source_startofpacket -> ARM_MCU_f2h_sdram0_data_agent_rsp_fifo:in_startofpacket
	wire          arm_mcu_f2h_sdram0_data_agent_rf_source_endofpacket;                  // ARM_MCU_f2h_sdram0_data_agent:rf_source_endofpacket -> ARM_MCU_f2h_sdram0_data_agent_rsp_fifo:in_endofpacket
	wire          arm_mcu_f2h_sdram0_data_agent_rsp_fifo_out_valid;                     // ARM_MCU_f2h_sdram0_data_agent_rsp_fifo:out_valid -> ARM_MCU_f2h_sdram0_data_agent:rf_sink_valid
	wire  [364:0] arm_mcu_f2h_sdram0_data_agent_rsp_fifo_out_data;                      // ARM_MCU_f2h_sdram0_data_agent_rsp_fifo:out_data -> ARM_MCU_f2h_sdram0_data_agent:rf_sink_data
	wire          arm_mcu_f2h_sdram0_data_agent_rsp_fifo_out_ready;                     // ARM_MCU_f2h_sdram0_data_agent:rf_sink_ready -> ARM_MCU_f2h_sdram0_data_agent_rsp_fifo:out_ready
	wire          arm_mcu_f2h_sdram0_data_agent_rsp_fifo_out_startofpacket;             // ARM_MCU_f2h_sdram0_data_agent_rsp_fifo:out_startofpacket -> ARM_MCU_f2h_sdram0_data_agent:rf_sink_startofpacket
	wire          arm_mcu_f2h_sdram0_data_agent_rsp_fifo_out_endofpacket;               // ARM_MCU_f2h_sdram0_data_agent_rsp_fifo:out_endofpacket -> ARM_MCU_f2h_sdram0_data_agent:rf_sink_endofpacket
	wire          jtag_debug_master_agent_cp_valid;                                     // JTAG_DEBUG_master_agent:cp_valid -> router:sink_valid
	wire  [111:0] jtag_debug_master_agent_cp_data;                                      // JTAG_DEBUG_master_agent:cp_data -> router:sink_data
	wire          jtag_debug_master_agent_cp_ready;                                     // router:sink_ready -> JTAG_DEBUG_master_agent:cp_ready
	wire          jtag_debug_master_agent_cp_startofpacket;                             // JTAG_DEBUG_master_agent:cp_startofpacket -> router:sink_startofpacket
	wire          jtag_debug_master_agent_cp_endofpacket;                               // JTAG_DEBUG_master_agent:cp_endofpacket -> router:sink_endofpacket
	wire          router_src_valid;                                                     // router:src_valid -> cmd_demux:sink_valid
	wire  [111:0] router_src_data;                                                      // router:src_data -> cmd_demux:sink_data
	wire          router_src_ready;                                                     // cmd_demux:sink_ready -> router:src_ready
	wire    [0:0] router_src_channel;                                                   // router:src_channel -> cmd_demux:sink_channel
	wire          router_src_startofpacket;                                             // router:src_startofpacket -> cmd_demux:sink_startofpacket
	wire          router_src_endofpacket;                                               // router:src_endofpacket -> cmd_demux:sink_endofpacket
	wire          arm_mcu_f2h_sdram0_data_agent_rp_valid;                               // ARM_MCU_f2h_sdram0_data_agent:rp_valid -> router_001:sink_valid
	wire  [363:0] arm_mcu_f2h_sdram0_data_agent_rp_data;                                // ARM_MCU_f2h_sdram0_data_agent:rp_data -> router_001:sink_data
	wire          arm_mcu_f2h_sdram0_data_agent_rp_ready;                               // router_001:sink_ready -> ARM_MCU_f2h_sdram0_data_agent:rp_ready
	wire          arm_mcu_f2h_sdram0_data_agent_rp_startofpacket;                       // ARM_MCU_f2h_sdram0_data_agent:rp_startofpacket -> router_001:sink_startofpacket
	wire          arm_mcu_f2h_sdram0_data_agent_rp_endofpacket;                         // ARM_MCU_f2h_sdram0_data_agent:rp_endofpacket -> router_001:sink_endofpacket
	wire          cmd_demux_src0_valid;                                                 // cmd_demux:src0_valid -> cmd_mux:sink0_valid
	wire  [111:0] cmd_demux_src0_data;                                                  // cmd_demux:src0_data -> cmd_mux:sink0_data
	wire          cmd_demux_src0_ready;                                                 // cmd_mux:sink0_ready -> cmd_demux:src0_ready
	wire    [0:0] cmd_demux_src0_channel;                                               // cmd_demux:src0_channel -> cmd_mux:sink0_channel
	wire          cmd_demux_src0_startofpacket;                                         // cmd_demux:src0_startofpacket -> cmd_mux:sink0_startofpacket
	wire          cmd_demux_src0_endofpacket;                                           // cmd_demux:src0_endofpacket -> cmd_mux:sink0_endofpacket
	wire          rsp_demux_src0_valid;                                                 // rsp_demux:src0_valid -> rsp_mux:sink0_valid
	wire  [111:0] rsp_demux_src0_data;                                                  // rsp_demux:src0_data -> rsp_mux:sink0_data
	wire          rsp_demux_src0_ready;                                                 // rsp_mux:sink0_ready -> rsp_demux:src0_ready
	wire    [0:0] rsp_demux_src0_channel;                                               // rsp_demux:src0_channel -> rsp_mux:sink0_channel
	wire          rsp_demux_src0_startofpacket;                                         // rsp_demux:src0_startofpacket -> rsp_mux:sink0_startofpacket
	wire          rsp_demux_src0_endofpacket;                                           // rsp_demux:src0_endofpacket -> rsp_mux:sink0_endofpacket
	wire          cmd_mux_src_valid;                                                    // cmd_mux:src_valid -> ARM_MCU_f2h_sdram0_data_cmd_width_adapter:in_valid
	wire  [111:0] cmd_mux_src_data;                                                     // cmd_mux:src_data -> ARM_MCU_f2h_sdram0_data_cmd_width_adapter:in_data
	wire          cmd_mux_src_ready;                                                    // ARM_MCU_f2h_sdram0_data_cmd_width_adapter:in_ready -> cmd_mux:src_ready
	wire    [0:0] cmd_mux_src_channel;                                                  // cmd_mux:src_channel -> ARM_MCU_f2h_sdram0_data_cmd_width_adapter:in_channel
	wire          cmd_mux_src_startofpacket;                                            // cmd_mux:src_startofpacket -> ARM_MCU_f2h_sdram0_data_cmd_width_adapter:in_startofpacket
	wire          cmd_mux_src_endofpacket;                                              // cmd_mux:src_endofpacket -> ARM_MCU_f2h_sdram0_data_cmd_width_adapter:in_endofpacket
	wire          arm_mcu_f2h_sdram0_data_cmd_width_adapter_src_valid;                  // ARM_MCU_f2h_sdram0_data_cmd_width_adapter:out_valid -> ARM_MCU_f2h_sdram0_data_agent:cp_valid
	wire  [363:0] arm_mcu_f2h_sdram0_data_cmd_width_adapter_src_data;                   // ARM_MCU_f2h_sdram0_data_cmd_width_adapter:out_data -> ARM_MCU_f2h_sdram0_data_agent:cp_data
	wire          arm_mcu_f2h_sdram0_data_cmd_width_adapter_src_ready;                  // ARM_MCU_f2h_sdram0_data_agent:cp_ready -> ARM_MCU_f2h_sdram0_data_cmd_width_adapter:out_ready
	wire    [0:0] arm_mcu_f2h_sdram0_data_cmd_width_adapter_src_channel;                // ARM_MCU_f2h_sdram0_data_cmd_width_adapter:out_channel -> ARM_MCU_f2h_sdram0_data_agent:cp_channel
	wire          arm_mcu_f2h_sdram0_data_cmd_width_adapter_src_startofpacket;          // ARM_MCU_f2h_sdram0_data_cmd_width_adapter:out_startofpacket -> ARM_MCU_f2h_sdram0_data_agent:cp_startofpacket
	wire          arm_mcu_f2h_sdram0_data_cmd_width_adapter_src_endofpacket;            // ARM_MCU_f2h_sdram0_data_cmd_width_adapter:out_endofpacket -> ARM_MCU_f2h_sdram0_data_agent:cp_endofpacket
	wire          router_001_src_valid;                                                 // router_001:src_valid -> ARM_MCU_f2h_sdram0_data_rsp_width_adapter:in_valid
	wire  [363:0] router_001_src_data;                                                  // router_001:src_data -> ARM_MCU_f2h_sdram0_data_rsp_width_adapter:in_data
	wire          router_001_src_ready;                                                 // ARM_MCU_f2h_sdram0_data_rsp_width_adapter:in_ready -> router_001:src_ready
	wire    [0:0] router_001_src_channel;                                               // router_001:src_channel -> ARM_MCU_f2h_sdram0_data_rsp_width_adapter:in_channel
	wire          router_001_src_startofpacket;                                         // router_001:src_startofpacket -> ARM_MCU_f2h_sdram0_data_rsp_width_adapter:in_startofpacket
	wire          router_001_src_endofpacket;                                           // router_001:src_endofpacket -> ARM_MCU_f2h_sdram0_data_rsp_width_adapter:in_endofpacket
	wire          arm_mcu_f2h_sdram0_data_rsp_width_adapter_src_valid;                  // ARM_MCU_f2h_sdram0_data_rsp_width_adapter:out_valid -> rsp_demux:sink_valid
	wire  [111:0] arm_mcu_f2h_sdram0_data_rsp_width_adapter_src_data;                   // ARM_MCU_f2h_sdram0_data_rsp_width_adapter:out_data -> rsp_demux:sink_data
	wire          arm_mcu_f2h_sdram0_data_rsp_width_adapter_src_ready;                  // rsp_demux:sink_ready -> ARM_MCU_f2h_sdram0_data_rsp_width_adapter:out_ready
	wire    [0:0] arm_mcu_f2h_sdram0_data_rsp_width_adapter_src_channel;                // ARM_MCU_f2h_sdram0_data_rsp_width_adapter:out_channel -> rsp_demux:sink_channel
	wire          arm_mcu_f2h_sdram0_data_rsp_width_adapter_src_startofpacket;          // ARM_MCU_f2h_sdram0_data_rsp_width_adapter:out_startofpacket -> rsp_demux:sink_startofpacket
	wire          arm_mcu_f2h_sdram0_data_rsp_width_adapter_src_endofpacket;            // ARM_MCU_f2h_sdram0_data_rsp_width_adapter:out_endofpacket -> rsp_demux:sink_endofpacket
	wire          arm_mcu_f2h_sdram0_data_agent_rdata_fifo_src_valid;                   // ARM_MCU_f2h_sdram0_data_agent:rdata_fifo_src_valid -> avalon_st_adapter:in_0_valid
	wire  [257:0] arm_mcu_f2h_sdram0_data_agent_rdata_fifo_src_data;                    // ARM_MCU_f2h_sdram0_data_agent:rdata_fifo_src_data -> avalon_st_adapter:in_0_data
	wire          arm_mcu_f2h_sdram0_data_agent_rdata_fifo_src_ready;                   // avalon_st_adapter:in_0_ready -> ARM_MCU_f2h_sdram0_data_agent:rdata_fifo_src_ready
	wire          avalon_st_adapter_out_0_valid;                                        // avalon_st_adapter:out_0_valid -> ARM_MCU_f2h_sdram0_data_agent:rdata_fifo_sink_valid
	wire  [257:0] avalon_st_adapter_out_0_data;                                         // avalon_st_adapter:out_0_data -> ARM_MCU_f2h_sdram0_data_agent:rdata_fifo_sink_data
	wire          avalon_st_adapter_out_0_ready;                                        // ARM_MCU_f2h_sdram0_data_agent:rdata_fifo_sink_ready -> avalon_st_adapter:out_0_ready
	wire    [0:0] avalon_st_adapter_out_0_error;                                        // avalon_st_adapter:out_0_error -> ARM_MCU_f2h_sdram0_data_agent:rdata_fifo_sink_error

	altera_merlin_master_translator #(
		.AV_ADDRESS_W                (32),
		.AV_DATA_W                   (32),
		.AV_BURSTCOUNT_W             (1),
		.AV_BYTEENABLE_W             (4),
		.UAV_ADDRESS_W               (32),
		.UAV_BURSTCOUNT_W            (3),
		.USE_READ                    (1),
		.USE_WRITE                   (1),
		.USE_BEGINBURSTTRANSFER      (0),
		.USE_BEGINTRANSFER           (0),
		.USE_CHIPSELECT              (0),
		.USE_BURSTCOUNT              (0),
		.USE_READDATAVALID           (1),
		.USE_WAITREQUEST             (1),
		.USE_READRESPONSE            (0),
		.USE_WRITERESPONSE           (0),
		.AV_SYMBOLS_PER_WORD         (4),
		.AV_ADDRESS_SYMBOLS          (1),
		.AV_BURSTCOUNT_SYMBOLS       (0),
		.AV_CONSTANT_BURST_BEHAVIOR  (0),
		.UAV_CONSTANT_BURST_BEHAVIOR (0),
		.AV_LINEWRAPBURSTS           (0),
		.AV_REGISTERINCOMINGSIGNALS  (0)
	) jtag_debug_master_translator (
		.clk                    (CLOCK_clk_clk),                                                        //                       clk.clk
		.reset                  (JTAG_DEBUG_master_translator_reset_reset_bridge_in_reset_reset),       //                     reset.reset
		.uav_address            (jtag_debug_master_translator_avalon_universal_master_0_address),       // avalon_universal_master_0.address
		.uav_burstcount         (jtag_debug_master_translator_avalon_universal_master_0_burstcount),    //                          .burstcount
		.uav_read               (jtag_debug_master_translator_avalon_universal_master_0_read),          //                          .read
		.uav_write              (jtag_debug_master_translator_avalon_universal_master_0_write),         //                          .write
		.uav_waitrequest        (jtag_debug_master_translator_avalon_universal_master_0_waitrequest),   //                          .waitrequest
		.uav_readdatavalid      (jtag_debug_master_translator_avalon_universal_master_0_readdatavalid), //                          .readdatavalid
		.uav_byteenable         (jtag_debug_master_translator_avalon_universal_master_0_byteenable),    //                          .byteenable
		.uav_readdata           (jtag_debug_master_translator_avalon_universal_master_0_readdata),      //                          .readdata
		.uav_writedata          (jtag_debug_master_translator_avalon_universal_master_0_writedata),     //                          .writedata
		.uav_lock               (jtag_debug_master_translator_avalon_universal_master_0_lock),          //                          .lock
		.uav_debugaccess        (jtag_debug_master_translator_avalon_universal_master_0_debugaccess),   //                          .debugaccess
		.av_address             (JTAG_DEBUG_master_address),                                            //      avalon_anti_master_0.address
		.av_waitrequest         (JTAG_DEBUG_master_waitrequest),                                        //                          .waitrequest
		.av_byteenable          (JTAG_DEBUG_master_byteenable),                                         //                          .byteenable
		.av_read                (JTAG_DEBUG_master_read),                                               //                          .read
		.av_readdata            (JTAG_DEBUG_master_readdata),                                           //                          .readdata
		.av_readdatavalid       (JTAG_DEBUG_master_readdatavalid),                                      //                          .readdatavalid
		.av_write               (JTAG_DEBUG_master_write),                                              //                          .write
		.av_writedata           (JTAG_DEBUG_master_writedata),                                          //                          .writedata
		.av_burstcount          (1'b1),                                                                 //               (terminated)
		.av_beginbursttransfer  (1'b0),                                                                 //               (terminated)
		.av_begintransfer       (1'b0),                                                                 //               (terminated)
		.av_chipselect          (1'b0),                                                                 //               (terminated)
		.av_lock                (1'b0),                                                                 //               (terminated)
		.av_debugaccess         (1'b0),                                                                 //               (terminated)
		.uav_clken              (),                                                                     //               (terminated)
		.av_clken               (1'b1),                                                                 //               (terminated)
		.uav_response           (2'b00),                                                                //               (terminated)
		.av_response            (),                                                                     //               (terminated)
		.uav_writeresponsevalid (1'b0),                                                                 //               (terminated)
		.av_writeresponsevalid  ()                                                                      //               (terminated)
	);

	altera_merlin_slave_translator #(
		.AV_ADDRESS_W                   (27),
		.AV_DATA_W                      (256),
		.UAV_DATA_W                     (256),
		.AV_BURSTCOUNT_W                (8),
		.AV_BYTEENABLE_W                (32),
		.UAV_BYTEENABLE_W               (32),
		.UAV_ADDRESS_W                  (32),
		.UAV_BURSTCOUNT_W               (13),
		.AV_READLATENCY                 (0),
		.USE_READDATAVALID              (1),
		.USE_WAITREQUEST                (1),
		.USE_UAV_CLKEN                  (0),
		.USE_READRESPONSE               (0),
		.USE_WRITERESPONSE              (0),
		.AV_SYMBOLS_PER_WORD            (32),
		.AV_ADDRESS_SYMBOLS             (0),
		.AV_BURSTCOUNT_SYMBOLS          (0),
		.AV_CONSTANT_BURST_BEHAVIOR     (0),
		.UAV_CONSTANT_BURST_BEHAVIOR    (0),
		.AV_REQUIRE_UNALIGNED_ADDRESSES (0),
		.CHIPSELECT_THROUGH_READLATENCY (0),
		.AV_READ_WAIT_CYCLES            (1),
		.AV_WRITE_WAIT_CYCLES           (0),
		.AV_SETUP_WAIT_CYCLES           (0),
		.AV_DATA_HOLD_CYCLES            (0)
	) arm_mcu_f2h_sdram0_data_translator (
		.clk                    (CLOCK_clk_clk),                                                        //                      clk.clk
		.reset                  (ARM_MCU_f2h_sdram0_data_translator_reset_reset_bridge_in_reset_reset), //                    reset.reset
		.uav_address            (arm_mcu_f2h_sdram0_data_agent_m0_address),                             // avalon_universal_slave_0.address
		.uav_burstcount         (arm_mcu_f2h_sdram0_data_agent_m0_burstcount),                          //                         .burstcount
		.uav_read               (arm_mcu_f2h_sdram0_data_agent_m0_read),                                //                         .read
		.uav_write              (arm_mcu_f2h_sdram0_data_agent_m0_write),                               //                         .write
		.uav_waitrequest        (arm_mcu_f2h_sdram0_data_agent_m0_waitrequest),                         //                         .waitrequest
		.uav_readdatavalid      (arm_mcu_f2h_sdram0_data_agent_m0_readdatavalid),                       //                         .readdatavalid
		.uav_byteenable         (arm_mcu_f2h_sdram0_data_agent_m0_byteenable),                          //                         .byteenable
		.uav_readdata           (arm_mcu_f2h_sdram0_data_agent_m0_readdata),                            //                         .readdata
		.uav_writedata          (arm_mcu_f2h_sdram0_data_agent_m0_writedata),                           //                         .writedata
		.uav_lock               (arm_mcu_f2h_sdram0_data_agent_m0_lock),                                //                         .lock
		.uav_debugaccess        (arm_mcu_f2h_sdram0_data_agent_m0_debugaccess),                         //                         .debugaccess
		.av_address             (ARM_MCU_f2h_sdram0_data_address),                                      //      avalon_anti_slave_0.address
		.av_write               (ARM_MCU_f2h_sdram0_data_write),                                        //                         .write
		.av_read                (ARM_MCU_f2h_sdram0_data_read),                                         //                         .read
		.av_readdata            (ARM_MCU_f2h_sdram0_data_readdata),                                     //                         .readdata
		.av_writedata           (ARM_MCU_f2h_sdram0_data_writedata),                                    //                         .writedata
		.av_burstcount          (ARM_MCU_f2h_sdram0_data_burstcount),                                   //                         .burstcount
		.av_byteenable          (ARM_MCU_f2h_sdram0_data_byteenable),                                   //                         .byteenable
		.av_readdatavalid       (ARM_MCU_f2h_sdram0_data_readdatavalid),                                //                         .readdatavalid
		.av_waitrequest         (ARM_MCU_f2h_sdram0_data_waitrequest),                                  //                         .waitrequest
		.av_begintransfer       (),                                                                     //              (terminated)
		.av_beginbursttransfer  (),                                                                     //              (terminated)
		.av_writebyteenable     (),                                                                     //              (terminated)
		.av_lock                (),                                                                     //              (terminated)
		.av_chipselect          (),                                                                     //              (terminated)
		.av_clken               (),                                                                     //              (terminated)
		.uav_clken              (1'b0),                                                                 //              (terminated)
		.av_debugaccess         (),                                                                     //              (terminated)
		.av_outputenable        (),                                                                     //              (terminated)
		.uav_response           (),                                                                     //              (terminated)
		.av_response            (2'b00),                                                                //              (terminated)
		.uav_writeresponsevalid (),                                                                     //              (terminated)
		.av_writeresponsevalid  (1'b0)                                                                  //              (terminated)
	);

	altera_merlin_master_agent #(
		.PKT_ORI_BURST_SIZE_H      (111),
		.PKT_ORI_BURST_SIZE_L      (109),
		.PKT_RESPONSE_STATUS_H     (108),
		.PKT_RESPONSE_STATUS_L     (107),
		.PKT_QOS_H                 (96),
		.PKT_QOS_L                 (96),
		.PKT_DATA_SIDEBAND_H       (94),
		.PKT_DATA_SIDEBAND_L       (94),
		.PKT_ADDR_SIDEBAND_H       (93),
		.PKT_ADDR_SIDEBAND_L       (93),
		.PKT_BURST_TYPE_H          (92),
		.PKT_BURST_TYPE_L          (91),
		.PKT_CACHE_H               (106),
		.PKT_CACHE_L               (103),
		.PKT_THREAD_ID_H           (99),
		.PKT_THREAD_ID_L           (99),
		.PKT_BURST_SIZE_H          (90),
		.PKT_BURST_SIZE_L          (88),
		.PKT_TRANS_EXCLUSIVE       (73),
		.PKT_TRANS_LOCK            (72),
		.PKT_BEGIN_BURST           (95),
		.PKT_PROTECTION_H          (102),
		.PKT_PROTECTION_L          (100),
		.PKT_BURSTWRAP_H           (87),
		.PKT_BURSTWRAP_L           (87),
		.PKT_BYTE_CNT_H            (86),
		.PKT_BYTE_CNT_L            (74),
		.PKT_ADDR_H                (67),
		.PKT_ADDR_L                (36),
		.PKT_TRANS_COMPRESSED_READ (68),
		.PKT_TRANS_POSTED          (69),
		.PKT_TRANS_WRITE           (70),
		.PKT_TRANS_READ            (71),
		.PKT_DATA_H                (31),
		.PKT_DATA_L                (0),
		.PKT_BYTEEN_H              (35),
		.PKT_BYTEEN_L              (32),
		.PKT_SRC_ID_H              (97),
		.PKT_SRC_ID_L              (97),
		.PKT_DEST_ID_H             (98),
		.PKT_DEST_ID_L             (98),
		.ST_DATA_W                 (112),
		.ST_CHANNEL_W              (1),
		.AV_BURSTCOUNT_W           (3),
		.SUPPRESS_0_BYTEEN_RSP     (1),
		.ID                        (0),
		.BURSTWRAP_VALUE           (1),
		.CACHE_VALUE               (0),
		.SECURE_ACCESS_BIT         (1),
		.USE_READRESPONSE          (0),
		.USE_WRITERESPONSE         (0)
	) jtag_debug_master_agent (
		.clk                   (CLOCK_clk_clk),                                                        //       clk.clk
		.reset                 (JTAG_DEBUG_master_translator_reset_reset_bridge_in_reset_reset),       // clk_reset.reset
		.av_address            (jtag_debug_master_translator_avalon_universal_master_0_address),       //        av.address
		.av_write              (jtag_debug_master_translator_avalon_universal_master_0_write),         //          .write
		.av_read               (jtag_debug_master_translator_avalon_universal_master_0_read),          //          .read
		.av_writedata          (jtag_debug_master_translator_avalon_universal_master_0_writedata),     //          .writedata
		.av_readdata           (jtag_debug_master_translator_avalon_universal_master_0_readdata),      //          .readdata
		.av_waitrequest        (jtag_debug_master_translator_avalon_universal_master_0_waitrequest),   //          .waitrequest
		.av_readdatavalid      (jtag_debug_master_translator_avalon_universal_master_0_readdatavalid), //          .readdatavalid
		.av_byteenable         (jtag_debug_master_translator_avalon_universal_master_0_byteenable),    //          .byteenable
		.av_burstcount         (jtag_debug_master_translator_avalon_universal_master_0_burstcount),    //          .burstcount
		.av_debugaccess        (jtag_debug_master_translator_avalon_universal_master_0_debugaccess),   //          .debugaccess
		.av_lock               (jtag_debug_master_translator_avalon_universal_master_0_lock),          //          .lock
		.cp_valid              (jtag_debug_master_agent_cp_valid),                                     //        cp.valid
		.cp_data               (jtag_debug_master_agent_cp_data),                                      //          .data
		.cp_startofpacket      (jtag_debug_master_agent_cp_startofpacket),                             //          .startofpacket
		.cp_endofpacket        (jtag_debug_master_agent_cp_endofpacket),                               //          .endofpacket
		.cp_ready              (jtag_debug_master_agent_cp_ready),                                     //          .ready
		.rp_valid              (rsp_mux_src_valid),                                                    //        rp.valid
		.rp_data               (rsp_mux_src_data),                                                     //          .data
		.rp_channel            (rsp_mux_src_channel),                                                  //          .channel
		.rp_startofpacket      (rsp_mux_src_startofpacket),                                            //          .startofpacket
		.rp_endofpacket        (rsp_mux_src_endofpacket),                                              //          .endofpacket
		.rp_ready              (rsp_mux_src_ready),                                                    //          .ready
		.av_response           (),                                                                     // (terminated)
		.av_writeresponsevalid ()                                                                      // (terminated)
	);

	altera_merlin_slave_agent #(
		.PKT_ORI_BURST_SIZE_H      (363),
		.PKT_ORI_BURST_SIZE_L      (361),
		.PKT_RESPONSE_STATUS_H     (360),
		.PKT_RESPONSE_STATUS_L     (359),
		.PKT_BURST_SIZE_H          (342),
		.PKT_BURST_SIZE_L          (340),
		.PKT_TRANS_LOCK            (324),
		.PKT_BEGIN_BURST           (347),
		.PKT_PROTECTION_H          (354),
		.PKT_PROTECTION_L          (352),
		.PKT_BURSTWRAP_H           (339),
		.PKT_BURSTWRAP_L           (339),
		.PKT_BYTE_CNT_H            (338),
		.PKT_BYTE_CNT_L            (326),
		.PKT_ADDR_H                (319),
		.PKT_ADDR_L                (288),
		.PKT_TRANS_COMPRESSED_READ (320),
		.PKT_TRANS_POSTED          (321),
		.PKT_TRANS_WRITE           (322),
		.PKT_TRANS_READ            (323),
		.PKT_DATA_H                (255),
		.PKT_DATA_L                (0),
		.PKT_BYTEEN_H              (287),
		.PKT_BYTEEN_L              (256),
		.PKT_SRC_ID_H              (349),
		.PKT_SRC_ID_L              (349),
		.PKT_DEST_ID_H             (350),
		.PKT_DEST_ID_L             (350),
		.PKT_SYMBOL_W              (8),
		.ST_CHANNEL_W              (1),
		.ST_DATA_W                 (364),
		.AVS_BURSTCOUNT_W          (13),
		.SUPPRESS_0_BYTEEN_CMD     (0),
		.PREVENT_FIFO_OVERFLOW     (1),
		.USE_READRESPONSE          (0),
		.USE_WRITERESPONSE         (0),
		.ECC_ENABLE                (0)
	) arm_mcu_f2h_sdram0_data_agent (
		.clk                     (CLOCK_clk_clk),                                                        //             clk.clk
		.reset                   (ARM_MCU_f2h_sdram0_data_translator_reset_reset_bridge_in_reset_reset), //       clk_reset.reset
		.m0_address              (arm_mcu_f2h_sdram0_data_agent_m0_address),                             //              m0.address
		.m0_burstcount           (arm_mcu_f2h_sdram0_data_agent_m0_burstcount),                          //                .burstcount
		.m0_byteenable           (arm_mcu_f2h_sdram0_data_agent_m0_byteenable),                          //                .byteenable
		.m0_debugaccess          (arm_mcu_f2h_sdram0_data_agent_m0_debugaccess),                         //                .debugaccess
		.m0_lock                 (arm_mcu_f2h_sdram0_data_agent_m0_lock),                                //                .lock
		.m0_readdata             (arm_mcu_f2h_sdram0_data_agent_m0_readdata),                            //                .readdata
		.m0_readdatavalid        (arm_mcu_f2h_sdram0_data_agent_m0_readdatavalid),                       //                .readdatavalid
		.m0_read                 (arm_mcu_f2h_sdram0_data_agent_m0_read),                                //                .read
		.m0_waitrequest          (arm_mcu_f2h_sdram0_data_agent_m0_waitrequest),                         //                .waitrequest
		.m0_writedata            (arm_mcu_f2h_sdram0_data_agent_m0_writedata),                           //                .writedata
		.m0_write                (arm_mcu_f2h_sdram0_data_agent_m0_write),                               //                .write
		.rp_endofpacket          (arm_mcu_f2h_sdram0_data_agent_rp_endofpacket),                         //              rp.endofpacket
		.rp_ready                (arm_mcu_f2h_sdram0_data_agent_rp_ready),                               //                .ready
		.rp_valid                (arm_mcu_f2h_sdram0_data_agent_rp_valid),                               //                .valid
		.rp_data                 (arm_mcu_f2h_sdram0_data_agent_rp_data),                                //                .data
		.rp_startofpacket        (arm_mcu_f2h_sdram0_data_agent_rp_startofpacket),                       //                .startofpacket
		.cp_ready                (arm_mcu_f2h_sdram0_data_cmd_width_adapter_src_ready),                  //              cp.ready
		.cp_valid                (arm_mcu_f2h_sdram0_data_cmd_width_adapter_src_valid),                  //                .valid
		.cp_data                 (arm_mcu_f2h_sdram0_data_cmd_width_adapter_src_data),                   //                .data
		.cp_startofpacket        (arm_mcu_f2h_sdram0_data_cmd_width_adapter_src_startofpacket),          //                .startofpacket
		.cp_endofpacket          (arm_mcu_f2h_sdram0_data_cmd_width_adapter_src_endofpacket),            //                .endofpacket
		.cp_channel              (arm_mcu_f2h_sdram0_data_cmd_width_adapter_src_channel),                //                .channel
		.rf_sink_ready           (arm_mcu_f2h_sdram0_data_agent_rsp_fifo_out_ready),                     //         rf_sink.ready
		.rf_sink_valid           (arm_mcu_f2h_sdram0_data_agent_rsp_fifo_out_valid),                     //                .valid
		.rf_sink_startofpacket   (arm_mcu_f2h_sdram0_data_agent_rsp_fifo_out_startofpacket),             //                .startofpacket
		.rf_sink_endofpacket     (arm_mcu_f2h_sdram0_data_agent_rsp_fifo_out_endofpacket),               //                .endofpacket
		.rf_sink_data            (arm_mcu_f2h_sdram0_data_agent_rsp_fifo_out_data),                      //                .data
		.rf_source_ready         (arm_mcu_f2h_sdram0_data_agent_rf_source_ready),                        //       rf_source.ready
		.rf_source_valid         (arm_mcu_f2h_sdram0_data_agent_rf_source_valid),                        //                .valid
		.rf_source_startofpacket (arm_mcu_f2h_sdram0_data_agent_rf_source_startofpacket),                //                .startofpacket
		.rf_source_endofpacket   (arm_mcu_f2h_sdram0_data_agent_rf_source_endofpacket),                  //                .endofpacket
		.rf_source_data          (arm_mcu_f2h_sdram0_data_agent_rf_source_data),                         //                .data
		.rdata_fifo_sink_ready   (avalon_st_adapter_out_0_ready),                                        // rdata_fifo_sink.ready
		.rdata_fifo_sink_valid   (avalon_st_adapter_out_0_valid),                                        //                .valid
		.rdata_fifo_sink_data    (avalon_st_adapter_out_0_data),                                         //                .data
		.rdata_fifo_sink_error   (avalon_st_adapter_out_0_error),                                        //                .error
		.rdata_fifo_src_ready    (arm_mcu_f2h_sdram0_data_agent_rdata_fifo_src_ready),                   //  rdata_fifo_src.ready
		.rdata_fifo_src_valid    (arm_mcu_f2h_sdram0_data_agent_rdata_fifo_src_valid),                   //                .valid
		.rdata_fifo_src_data     (arm_mcu_f2h_sdram0_data_agent_rdata_fifo_src_data),                    //                .data
		.m0_response             (2'b00),                                                                //     (terminated)
		.m0_writeresponsevalid   (1'b0)                                                                  //     (terminated)
	);

	altera_avalon_sc_fifo #(
		.SYMBOLS_PER_BEAT    (1),
		.BITS_PER_SYMBOL     (365),
		.FIFO_DEPTH          (15),
		.CHANNEL_WIDTH       (0),
		.ERROR_WIDTH         (0),
		.USE_PACKETS         (1),
		.USE_FILL_LEVEL      (0),
		.EMPTY_LATENCY       (1),
		.USE_MEMORY_BLOCKS   (0),
		.USE_STORE_FORWARD   (0),
		.USE_ALMOST_FULL_IF  (0),
		.USE_ALMOST_EMPTY_IF (0)
	) arm_mcu_f2h_sdram0_data_agent_rsp_fifo (
		.clk               (CLOCK_clk_clk),                                                        //       clk.clk
		.reset             (ARM_MCU_f2h_sdram0_data_translator_reset_reset_bridge_in_reset_reset), // clk_reset.reset
		.in_data           (arm_mcu_f2h_sdram0_data_agent_rf_source_data),                         //        in.data
		.in_valid          (arm_mcu_f2h_sdram0_data_agent_rf_source_valid),                        //          .valid
		.in_ready          (arm_mcu_f2h_sdram0_data_agent_rf_source_ready),                        //          .ready
		.in_startofpacket  (arm_mcu_f2h_sdram0_data_agent_rf_source_startofpacket),                //          .startofpacket
		.in_endofpacket    (arm_mcu_f2h_sdram0_data_agent_rf_source_endofpacket),                  //          .endofpacket
		.out_data          (arm_mcu_f2h_sdram0_data_agent_rsp_fifo_out_data),                      //       out.data
		.out_valid         (arm_mcu_f2h_sdram0_data_agent_rsp_fifo_out_valid),                     //          .valid
		.out_ready         (arm_mcu_f2h_sdram0_data_agent_rsp_fifo_out_ready),                     //          .ready
		.out_startofpacket (arm_mcu_f2h_sdram0_data_agent_rsp_fifo_out_startofpacket),             //          .startofpacket
		.out_endofpacket   (arm_mcu_f2h_sdram0_data_agent_rsp_fifo_out_endofpacket),               //          .endofpacket
		.csr_address       (2'b00),                                                                // (terminated)
		.csr_read          (1'b0),                                                                 // (terminated)
		.csr_write         (1'b0),                                                                 // (terminated)
		.csr_readdata      (),                                                                     // (terminated)
		.csr_writedata     (32'b00000000000000000000000000000000),                                 // (terminated)
		.almost_full_data  (),                                                                     // (terminated)
		.almost_empty_data (),                                                                     // (terminated)
		.in_empty          (1'b0),                                                                 // (terminated)
		.out_empty         (),                                                                     // (terminated)
		.in_error          (1'b0),                                                                 // (terminated)
		.out_error         (),                                                                     // (terminated)
		.in_channel        (1'b0),                                                                 // (terminated)
		.out_channel       ()                                                                      // (terminated)
	);

	ledtest_mm_interconnect_2_router router (
		.sink_ready         (jtag_debug_master_agent_cp_ready),                               //      sink.ready
		.sink_valid         (jtag_debug_master_agent_cp_valid),                               //          .valid
		.sink_data          (jtag_debug_master_agent_cp_data),                                //          .data
		.sink_startofpacket (jtag_debug_master_agent_cp_startofpacket),                       //          .startofpacket
		.sink_endofpacket   (jtag_debug_master_agent_cp_endofpacket),                         //          .endofpacket
		.clk                (CLOCK_clk_clk),                                                  //       clk.clk
		.reset              (JTAG_DEBUG_master_translator_reset_reset_bridge_in_reset_reset), // clk_reset.reset
		.src_ready          (router_src_ready),                                               //       src.ready
		.src_valid          (router_src_valid),                                               //          .valid
		.src_data           (router_src_data),                                                //          .data
		.src_channel        (router_src_channel),                                             //          .channel
		.src_startofpacket  (router_src_startofpacket),                                       //          .startofpacket
		.src_endofpacket    (router_src_endofpacket)                                          //          .endofpacket
	);

	ledtest_mm_interconnect_2_router_001 router_001 (
		.sink_ready         (arm_mcu_f2h_sdram0_data_agent_rp_ready),                               //      sink.ready
		.sink_valid         (arm_mcu_f2h_sdram0_data_agent_rp_valid),                               //          .valid
		.sink_data          (arm_mcu_f2h_sdram0_data_agent_rp_data),                                //          .data
		.sink_startofpacket (arm_mcu_f2h_sdram0_data_agent_rp_startofpacket),                       //          .startofpacket
		.sink_endofpacket   (arm_mcu_f2h_sdram0_data_agent_rp_endofpacket),                         //          .endofpacket
		.clk                (CLOCK_clk_clk),                                                        //       clk.clk
		.reset              (ARM_MCU_f2h_sdram0_data_translator_reset_reset_bridge_in_reset_reset), // clk_reset.reset
		.src_ready          (router_001_src_ready),                                                 //       src.ready
		.src_valid          (router_001_src_valid),                                                 //          .valid
		.src_data           (router_001_src_data),                                                  //          .data
		.src_channel        (router_001_src_channel),                                               //          .channel
		.src_startofpacket  (router_001_src_startofpacket),                                         //          .startofpacket
		.src_endofpacket    (router_001_src_endofpacket)                                            //          .endofpacket
	);

	ledtest_mm_interconnect_2_cmd_demux cmd_demux (
		.clk                (CLOCK_clk_clk),                                                  //       clk.clk
		.reset              (JTAG_DEBUG_master_translator_reset_reset_bridge_in_reset_reset), // clk_reset.reset
		.sink_ready         (router_src_ready),                                               //      sink.ready
		.sink_channel       (router_src_channel),                                             //          .channel
		.sink_data          (router_src_data),                                                //          .data
		.sink_startofpacket (router_src_startofpacket),                                       //          .startofpacket
		.sink_endofpacket   (router_src_endofpacket),                                         //          .endofpacket
		.sink_valid         (router_src_valid),                                               //          .valid
		.src0_ready         (cmd_demux_src0_ready),                                           //      src0.ready
		.src0_valid         (cmd_demux_src0_valid),                                           //          .valid
		.src0_data          (cmd_demux_src0_data),                                            //          .data
		.src0_channel       (cmd_demux_src0_channel),                                         //          .channel
		.src0_startofpacket (cmd_demux_src0_startofpacket),                                   //          .startofpacket
		.src0_endofpacket   (cmd_demux_src0_endofpacket)                                      //          .endofpacket
	);

	ledtest_mm_interconnect_2_cmd_mux cmd_mux (
		.clk                 (CLOCK_clk_clk),                                                        //       clk.clk
		.reset               (ARM_MCU_f2h_sdram0_data_translator_reset_reset_bridge_in_reset_reset), // clk_reset.reset
		.src_ready           (cmd_mux_src_ready),                                                    //       src.ready
		.src_valid           (cmd_mux_src_valid),                                                    //          .valid
		.src_data            (cmd_mux_src_data),                                                     //          .data
		.src_channel         (cmd_mux_src_channel),                                                  //          .channel
		.src_startofpacket   (cmd_mux_src_startofpacket),                                            //          .startofpacket
		.src_endofpacket     (cmd_mux_src_endofpacket),                                              //          .endofpacket
		.sink0_ready         (cmd_demux_src0_ready),                                                 //     sink0.ready
		.sink0_valid         (cmd_demux_src0_valid),                                                 //          .valid
		.sink0_channel       (cmd_demux_src0_channel),                                               //          .channel
		.sink0_data          (cmd_demux_src0_data),                                                  //          .data
		.sink0_startofpacket (cmd_demux_src0_startofpacket),                                         //          .startofpacket
		.sink0_endofpacket   (cmd_demux_src0_endofpacket)                                            //          .endofpacket
	);

	ledtest_mm_interconnect_2_cmd_demux rsp_demux (
		.clk                (CLOCK_clk_clk),                                                        //       clk.clk
		.reset              (ARM_MCU_f2h_sdram0_data_translator_reset_reset_bridge_in_reset_reset), // clk_reset.reset
		.sink_ready         (arm_mcu_f2h_sdram0_data_rsp_width_adapter_src_ready),                  //      sink.ready
		.sink_channel       (arm_mcu_f2h_sdram0_data_rsp_width_adapter_src_channel),                //          .channel
		.sink_data          (arm_mcu_f2h_sdram0_data_rsp_width_adapter_src_data),                   //          .data
		.sink_startofpacket (arm_mcu_f2h_sdram0_data_rsp_width_adapter_src_startofpacket),          //          .startofpacket
		.sink_endofpacket   (arm_mcu_f2h_sdram0_data_rsp_width_adapter_src_endofpacket),            //          .endofpacket
		.sink_valid         (arm_mcu_f2h_sdram0_data_rsp_width_adapter_src_valid),                  //          .valid
		.src0_ready         (rsp_demux_src0_ready),                                                 //      src0.ready
		.src0_valid         (rsp_demux_src0_valid),                                                 //          .valid
		.src0_data          (rsp_demux_src0_data),                                                  //          .data
		.src0_channel       (rsp_demux_src0_channel),                                               //          .channel
		.src0_startofpacket (rsp_demux_src0_startofpacket),                                         //          .startofpacket
		.src0_endofpacket   (rsp_demux_src0_endofpacket)                                            //          .endofpacket
	);

	ledtest_mm_interconnect_2_rsp_mux rsp_mux (
		.clk                 (CLOCK_clk_clk),                                                  //       clk.clk
		.reset               (JTAG_DEBUG_master_translator_reset_reset_bridge_in_reset_reset), // clk_reset.reset
		.src_ready           (rsp_mux_src_ready),                                              //       src.ready
		.src_valid           (rsp_mux_src_valid),                                              //          .valid
		.src_data            (rsp_mux_src_data),                                               //          .data
		.src_channel         (rsp_mux_src_channel),                                            //          .channel
		.src_startofpacket   (rsp_mux_src_startofpacket),                                      //          .startofpacket
		.src_endofpacket     (rsp_mux_src_endofpacket),                                        //          .endofpacket
		.sink0_ready         (rsp_demux_src0_ready),                                           //     sink0.ready
		.sink0_valid         (rsp_demux_src0_valid),                                           //          .valid
		.sink0_channel       (rsp_demux_src0_channel),                                         //          .channel
		.sink0_data          (rsp_demux_src0_data),                                            //          .data
		.sink0_startofpacket (rsp_demux_src0_startofpacket),                                   //          .startofpacket
		.sink0_endofpacket   (rsp_demux_src0_endofpacket)                                      //          .endofpacket
	);

	altera_merlin_width_adapter #(
		.IN_PKT_ADDR_H                 (67),
		.IN_PKT_ADDR_L                 (36),
		.IN_PKT_DATA_H                 (31),
		.IN_PKT_DATA_L                 (0),
		.IN_PKT_BYTEEN_H               (35),
		.IN_PKT_BYTEEN_L               (32),
		.IN_PKT_BYTE_CNT_H             (86),
		.IN_PKT_BYTE_CNT_L             (74),
		.IN_PKT_TRANS_COMPRESSED_READ  (68),
		.IN_PKT_TRANS_WRITE            (70),
		.IN_PKT_BURSTWRAP_H            (87),
		.IN_PKT_BURSTWRAP_L            (87),
		.IN_PKT_BURST_SIZE_H           (90),
		.IN_PKT_BURST_SIZE_L           (88),
		.IN_PKT_RESPONSE_STATUS_H      (108),
		.IN_PKT_RESPONSE_STATUS_L      (107),
		.IN_PKT_TRANS_EXCLUSIVE        (73),
		.IN_PKT_BURST_TYPE_H           (92),
		.IN_PKT_BURST_TYPE_L           (91),
		.IN_PKT_ORI_BURST_SIZE_L       (109),
		.IN_PKT_ORI_BURST_SIZE_H       (111),
		.IN_ST_DATA_W                  (112),
		.OUT_PKT_ADDR_H                (319),
		.OUT_PKT_ADDR_L                (288),
		.OUT_PKT_DATA_H                (255),
		.OUT_PKT_DATA_L                (0),
		.OUT_PKT_BYTEEN_H              (287),
		.OUT_PKT_BYTEEN_L              (256),
		.OUT_PKT_BYTE_CNT_H            (338),
		.OUT_PKT_BYTE_CNT_L            (326),
		.OUT_PKT_TRANS_COMPRESSED_READ (320),
		.OUT_PKT_BURST_SIZE_H          (342),
		.OUT_PKT_BURST_SIZE_L          (340),
		.OUT_PKT_RESPONSE_STATUS_H     (360),
		.OUT_PKT_RESPONSE_STATUS_L     (359),
		.OUT_PKT_TRANS_EXCLUSIVE       (325),
		.OUT_PKT_BURST_TYPE_H          (344),
		.OUT_PKT_BURST_TYPE_L          (343),
		.OUT_PKT_ORI_BURST_SIZE_L      (361),
		.OUT_PKT_ORI_BURST_SIZE_H      (363),
		.OUT_ST_DATA_W                 (364),
		.ST_CHANNEL_W                  (1),
		.OPTIMIZE_FOR_RSP              (0),
		.RESPONSE_PATH                 (0),
		.CONSTANT_BURST_SIZE           (1),
		.PACKING                       (1),
		.ENABLE_ADDRESS_ALIGNMENT      (0)
	) arm_mcu_f2h_sdram0_data_cmd_width_adapter (
		.clk                  (CLOCK_clk_clk),                                                        //       clk.clk
		.reset                (ARM_MCU_f2h_sdram0_data_translator_reset_reset_bridge_in_reset_reset), // clk_reset.reset
		.in_valid             (cmd_mux_src_valid),                                                    //      sink.valid
		.in_channel           (cmd_mux_src_channel),                                                  //          .channel
		.in_startofpacket     (cmd_mux_src_startofpacket),                                            //          .startofpacket
		.in_endofpacket       (cmd_mux_src_endofpacket),                                              //          .endofpacket
		.in_ready             (cmd_mux_src_ready),                                                    //          .ready
		.in_data              (cmd_mux_src_data),                                                     //          .data
		.out_endofpacket      (arm_mcu_f2h_sdram0_data_cmd_width_adapter_src_endofpacket),            //       src.endofpacket
		.out_data             (arm_mcu_f2h_sdram0_data_cmd_width_adapter_src_data),                   //          .data
		.out_channel          (arm_mcu_f2h_sdram0_data_cmd_width_adapter_src_channel),                //          .channel
		.out_valid            (arm_mcu_f2h_sdram0_data_cmd_width_adapter_src_valid),                  //          .valid
		.out_ready            (arm_mcu_f2h_sdram0_data_cmd_width_adapter_src_ready),                  //          .ready
		.out_startofpacket    (arm_mcu_f2h_sdram0_data_cmd_width_adapter_src_startofpacket),          //          .startofpacket
		.in_command_size_data (3'b000)                                                                // (terminated)
	);

	altera_merlin_width_adapter #(
		.IN_PKT_ADDR_H                 (319),
		.IN_PKT_ADDR_L                 (288),
		.IN_PKT_DATA_H                 (255),
		.IN_PKT_DATA_L                 (0),
		.IN_PKT_BYTEEN_H               (287),
		.IN_PKT_BYTEEN_L               (256),
		.IN_PKT_BYTE_CNT_H             (338),
		.IN_PKT_BYTE_CNT_L             (326),
		.IN_PKT_TRANS_COMPRESSED_READ  (320),
		.IN_PKT_TRANS_WRITE            (322),
		.IN_PKT_BURSTWRAP_H            (339),
		.IN_PKT_BURSTWRAP_L            (339),
		.IN_PKT_BURST_SIZE_H           (342),
		.IN_PKT_BURST_SIZE_L           (340),
		.IN_PKT_RESPONSE_STATUS_H      (360),
		.IN_PKT_RESPONSE_STATUS_L      (359),
		.IN_PKT_TRANS_EXCLUSIVE        (325),
		.IN_PKT_BURST_TYPE_H           (344),
		.IN_PKT_BURST_TYPE_L           (343),
		.IN_PKT_ORI_BURST_SIZE_L       (361),
		.IN_PKT_ORI_BURST_SIZE_H       (363),
		.IN_ST_DATA_W                  (364),
		.OUT_PKT_ADDR_H                (67),
		.OUT_PKT_ADDR_L                (36),
		.OUT_PKT_DATA_H                (31),
		.OUT_PKT_DATA_L                (0),
		.OUT_PKT_BYTEEN_H              (35),
		.OUT_PKT_BYTEEN_L              (32),
		.OUT_PKT_BYTE_CNT_H            (86),
		.OUT_PKT_BYTE_CNT_L            (74),
		.OUT_PKT_TRANS_COMPRESSED_READ (68),
		.OUT_PKT_BURST_SIZE_H          (90),
		.OUT_PKT_BURST_SIZE_L          (88),
		.OUT_PKT_RESPONSE_STATUS_H     (108),
		.OUT_PKT_RESPONSE_STATUS_L     (107),
		.OUT_PKT_TRANS_EXCLUSIVE       (73),
		.OUT_PKT_BURST_TYPE_H          (92),
		.OUT_PKT_BURST_TYPE_L          (91),
		.OUT_PKT_ORI_BURST_SIZE_L      (109),
		.OUT_PKT_ORI_BURST_SIZE_H      (111),
		.OUT_ST_DATA_W                 (112),
		.ST_CHANNEL_W                  (1),
		.OPTIMIZE_FOR_RSP              (1),
		.RESPONSE_PATH                 (1),
		.CONSTANT_BURST_SIZE           (1),
		.PACKING                       (1),
		.ENABLE_ADDRESS_ALIGNMENT      (0)
	) arm_mcu_f2h_sdram0_data_rsp_width_adapter (
		.clk                  (CLOCK_clk_clk),                                                        //       clk.clk
		.reset                (ARM_MCU_f2h_sdram0_data_translator_reset_reset_bridge_in_reset_reset), // clk_reset.reset
		.in_valid             (router_001_src_valid),                                                 //      sink.valid
		.in_channel           (router_001_src_channel),                                               //          .channel
		.in_startofpacket     (router_001_src_startofpacket),                                         //          .startofpacket
		.in_endofpacket       (router_001_src_endofpacket),                                           //          .endofpacket
		.in_ready             (router_001_src_ready),                                                 //          .ready
		.in_data              (router_001_src_data),                                                  //          .data
		.out_endofpacket      (arm_mcu_f2h_sdram0_data_rsp_width_adapter_src_endofpacket),            //       src.endofpacket
		.out_data             (arm_mcu_f2h_sdram0_data_rsp_width_adapter_src_data),                   //          .data
		.out_channel          (arm_mcu_f2h_sdram0_data_rsp_width_adapter_src_channel),                //          .channel
		.out_valid            (arm_mcu_f2h_sdram0_data_rsp_width_adapter_src_valid),                  //          .valid
		.out_ready            (arm_mcu_f2h_sdram0_data_rsp_width_adapter_src_ready),                  //          .ready
		.out_startofpacket    (arm_mcu_f2h_sdram0_data_rsp_width_adapter_src_startofpacket),          //          .startofpacket
		.in_command_size_data (3'b000)                                                                // (terminated)
	);

	ledtest_mm_interconnect_2_avalon_st_adapter #(
		.inBitsPerSymbol (258),
		.inUsePackets    (0),
		.inDataWidth     (258),
		.inChannelWidth  (0),
		.inErrorWidth    (0),
		.inUseEmptyPort  (0),
		.inUseValid      (1),
		.inUseReady      (1),
		.inReadyLatency  (0),
		.outDataWidth    (258),
		.outChannelWidth (0),
		.outErrorWidth   (1),
		.outUseEmptyPort (0),
		.outUseValid     (1),
		.outUseReady     (1),
		.outReadyLatency (0)
	) avalon_st_adapter (
		.in_clk_0_clk   (CLOCK_clk_clk),                                                        // in_clk_0.clk
		.in_rst_0_reset (ARM_MCU_f2h_sdram0_data_translator_reset_reset_bridge_in_reset_reset), // in_rst_0.reset
		.in_0_data      (arm_mcu_f2h_sdram0_data_agent_rdata_fifo_src_data),                    //     in_0.data
		.in_0_valid     (arm_mcu_f2h_sdram0_data_agent_rdata_fifo_src_valid),                   //         .valid
		.in_0_ready     (arm_mcu_f2h_sdram0_data_agent_rdata_fifo_src_ready),                   //         .ready
		.out_0_data     (avalon_st_adapter_out_0_data),                                         //    out_0.data
		.out_0_valid    (avalon_st_adapter_out_0_valid),                                        //         .valid
		.out_0_ready    (avalon_st_adapter_out_0_ready),                                        //         .ready
		.out_0_error    (avalon_st_adapter_out_0_error)                                         //         .error
	);

endmodule
